### ISSUE TITLE
migrate latest commits over

### ISSUE THREAD

**Issue by kevgo** [Originate/exocom#1]
__ExoCom__
- [x] exocom-mock-go: @martinjaime 
- [x] exocom-mock-js: @kevgo 
- [x] exocom-server @trushton
- [x] exorelay-go @martinjaime
- [x] exorelay-haskell
- [x] exorelay-java @hugobho 
- [x] exorelay-javascript @kevgo
- [x] exorelay-scala @kevgo
- [x] exoservice-javascript @kevgo

**Comment by martinjaime** [comment]
Reopening since exocom-mock-go was not migrated.
