### ISSUE TITLE
Fix connection to exocom server from go

### ISSUE THREAD

**Issue by stefansavev-o** [Originate/exocom#148]
File: github.com/Originate/exocom/go/exorelay/main.go
Wrong: socket, err := websocket.Dial(fmt.Sprintf("ws://%s:%d", e.Config.Host, e.Config.Port), "", "origin:")
Correct: socket, err := websocket.Dial(fmt.Sprintf("ws://%s:%d/services", e.Config.Host, e.Config.Port), "", "origin:")

**Comment by charlierudolph** [comment]
I don't think we can assume that everyone will make exocom available at `/services`. We can add a configuration option though so you could pass in "/services" and have that added to the path.

**Comment by charlierudolph** [comment]
@stefansavev-o would the configuration option that allows you set the path work?

**Comment by stefansavev-o** [comment]
Yes, it will work with a configuration option. However as it is now, it waits infinitely. The server never replies. Perhaps add a timeout and a reasonable error message to point to the cause and solution.

**Comment by charlierudolph** [comment]
Can you please create a separate issue for the timeout? That would probably need to be its own configuration option.

**Comment by charlierudolph** [comment]
Looking back at implementing this. How did you get exocom deployed at a non-root path? Looking at the code for exocom, you can only pass in a port.

**Comment by stefansavev-o** [comment]
I used this
```
function run_exocom(){
  declare -x PORT=$EXOCOM_PORT
  declare -x SERVICE_ROUTES="${ROUTES_DESC}"
  echo "Starting exocom"
  node node_modules/exocom-dev/dist/cli.js
}
```
Anyway, if you can pass a variable for `/services`, the issue will go away.
