### ISSUE TITLE
Exocom dumps large messages on the console

### ISSUE THREAD

**Issue by stefansavev-o** [Originate/exocom#152]
This is an issue especially if you don't pipe `exo run` to a file.
It causes timesouts of services.
Recommendation: only dump parts of large messages

**Comment by charlierudolph** [comment]
Can you be more specific about what is the exocom message that is too long? (maybe give some sample output). Hmm, maybe we should have different logging levels where by default we only log the message names and have another logging level which includes the message payload?

**Comment by stefansavev-o** [comment]
Different logging levels makes sense and also a limit on the message body that is dumped.

**Comment by charlierudolph** [comment]
Limit just being character limit (ie would dump the first 200 characters of the json)?

**Comment by stefansavev-o** [comment]
yes. I don't know about 200. Better to be a configuration that can be overridden.

**Comment by charlierudolph** [comment]
Moved this to https://github.com/Originate/exosphere/issues/326
