### ISSUE TITLE
If the exocome server does not reply within a few seconds return a timeout error (for go)

### ISSUE THREAD

**Issue by stefansavev-o** [Originate/exocom#157]
Right now it works like this
- go client creates a connect
- go client sends an initial message
- exocome client may or may not reply
- if the connection is not dropped, but no reply comes, return a special timeout error

**Comment by charlierudolph** [comment]
> If the exocome server does not reply within a few seconds return a timeout error (for go)

To my knowledge, exocom does not actually sends messages. It just broadcasts messages sent by services. 

---

What is the initial message? Is the builtin exorelay message `exocom.register-service` or one sent by the user? 

We could introduce a timeout configuration for sending a particular message which is the max amount of time you want to wait for a reply.

**Comment by stefansavev-o** [comment]
Just run exocom and try to connect from go and you'll see the issue. The go client just stays waiting.

**Comment by charlierudolph** [comment]
Just want to clarify exactly what you are asking for. Do you want to add a timeout for making the initial connection to exocom? Currently it continuously retries every 100 ms

**Comment by stefansavev-o** [comment]
So maybe timeout does not make sense. It only make sense to connect. I think this is a very technical condition that I observed in the nodejs implementation of websockets.

**Comment by charlierudolph** [comment]
So do we need to do anything here or can this be closed?

**Comment by stefansavev** [comment]
Sorry for the delay. I wanted to check the new code and I found it. The property is called Handshake timeout.
github.com/Originate/exocom/go/utils/websocket.go

func ConnectWithRetry(url string, delay int) (socket *websocket.Conn, err error) {
	Retry(delay, func() bool {
		mydialer := &websocket.Dialer{
			Proxy: http.ProxyFromEnvironment,
			HandshakeTimeout: 0, //hangs if set to 0 and services is wrong
		}
		socket, _, err = mydialer.Dial(url, nil)
		if err != nil {
			fmt.Printf("Unable to connect (%s). Retrying...\n", err)
			return false
		}
		return true
	})
	return socket, err
}

**Comment by charlierudolph** [comment]
Closing as now has endless retries when attempting to connect. Also corrected the issue of not connecting to `/services`.
