### ISSUE TITLE
exocom: refactor to subsytems

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exocom#181]
* cmd 
  * top level command parsing
  * create and start core
* core
   * creates a logger
   * creates an activity broadcaster
   * sets up the server
   * each time a websocket connects, create a service connector
   * when receives incoming message from service connector, add timestamp / responseTime data,  pass to activity broadcaster (will pass to other subsystems in the future)
* connection 
  * service connector 
    * properties: websocket connection, pointer to the core, pointer to logger
    * responsible for message translation (incoming and outgoing), validates service can send message with that name
    * passes incoming messages to the core
* broadcast 
    * activity broadcaster 
      * properties: pointer to map from role to service connector, pointer to core, pointer to logger
      * when receives outgoing messages from the core, responsible for passing to service connectors that receive that messages with that name, logs if no service receives it

@kevgo @mcharawi please review. Trying to follow the architecture diagram and determine where all the existing parts would live

**Comment by kevgo** [comment]
This is overall correct. What are your thoughts around subsystems signaling events to the core? Afaik Go does not have an event-emitter system. Maybe use channels and run all subsystems in goroutines?

**Comment by charlierudolph** [comment]
Yes, I think channels are the way to go.
