### ISSUE TITLE
update message translation to match documentation

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exocom#183]
[documentation/message_translation.md](https://github.com/Originate/exocom/blob/3a54e4b436eb210df3c4d2af0e0ef96201f49229/documentation/message_translation.md) appears to be out of date with the current implementation where you provide a namespace. 

@kevgo what should be updated here? The documentation or the implementation? I would guess the documentation

**Comment by kevgo** [comment]
This document describes the new way how message translation should work. We have to describe it in `application.yml`, since message translation is an application responsibility, and services themselves don't know about the application in which they are used.

**Comment by charlierudolph** [comment]
The messageTranslation will be passed in the service routes instead of namespace.

**Comment by mcharawi** [comment]
#209
