### ISSUE TITLE
go: rename websocketbridge

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exocom#184]
The docs refer to it as [FrontEnd Bridge](https://github.com/Originate/exocom/blob/3a54e4b436eb210df3c4d2af0e0ef96201f49229/documentation/frontend_bridge.md). I could also see naming it `sessionbridge` as each connection gets a new session id. I don't think websocket needs to be in the same as all of exocom is based on websockets. Could also be named something like `exobridge`. 

@kevgo @hugobho @mcharawi @cheahuychou thoughts?

**Comment by kevgo** [comment]
Technically this bridge creates connections to front-end clients. These can be browsers or mobile apps. Hence the name `Frontend Bridge`.
