### ISSUE TITLE
support for serviceType

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exocom#200]
The `./config.json` endpoint returns a `serviceType` for each client which in the JS code was being assigned the role. Is this suppose to have a different value for the case where a mongo service has the role `users` and the service type would be `mongo`? Where would the service type be coming from? Based on those assumptions, I would expect it to come in via the service routes and thus exosphere we need to be updated to support it. Then it could actually be removed from clients as it would be defined in routes.

@kevgo please let me know if my understand correct or how you would like to support this

**Comment by kevgo** [comment]
Is this endpoint used in the new Go implementation?

**Comment by charlierudolph** [comment]
The only place I see this being used is in the exocom tests. I'm not certain how you someone would use the endpoint

**Comment by kevgo** [comment]
Okay. I think we can leave the type out and just look at the roles here then.

**Comment by charlierudolph** [comment]
okay I will remove it then
