### ISSUE TITLE
security adapter: exosecurity

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exocom#217]
Wraps exorelay to provide an interface where the user defines a single function which takes in a message to authorize and a function to make a data request. The function returns a boolean (possibly in an asynchronous manner).

The function to make a data request puts the data request as the payload in a `security request` message retaining the activityId.

On the arrival of a `security response` message with the proper `activityId` it passes the message in the payload to wherever was waiting for that response. 

See #215 for an example of the what the outgoing and incoming requests should look like

**Comment by kevgo** [comment]
moving to exosphere repo
