### ISSUE TITLE
Sends messages null error

### ISSUE THREAD

**Issue by ben-goldberg** [Originate/exocom#92]
If the `sends:` section is empty in the `service.yml` file, and that service tries to send a message, exosphere crashes. The error points to the line below:

https://github.com/Originate/exocom/blob/master/exocom-server/src/client-registry/client-registry.ls#L42

The problem is that, from `@routing[sender-name].sends`, the `.sends` returns `null`. I'd expect you'd want to gracefully fail and throw an error with a message like: "no send messages are defined in the service.yml file" or something to that effect.

**Comment by ben-goldberg** [comment]
@kevgo

**Comment by kevgo** [comment]
Good point. We should probably just do nothing here, or default the content of `sends` to `[]` instead of `null`. But, is there ever a service that does not send messages?

**Comment by ben-goldberg** [comment]
It was a mistake on my part, having accidentally left the `sends` section blank in `service.yml`. And the error didn't happen until I tried to send a message. But it took me a long time to track down the error since the problem manifested in exosphere crashing with an uninformative error.

**Comment by kevgo** [comment]
Agreed that we should display a more helpful error message for this user error. Ideally something like "you are trying to send the message XXX, but your service is not permitted to do so. Please update the 'sends' section in service.yml".
